# server （eureka默认端口为：8761）
server:
  port: 8761
  # 服务名
spring:
  application:
    name: discovery-eureka-server
  # 是否注册到eureka（eureka本身是不需要再注册到自己的）
eureka:
  client:
    register-with-eureka: false
  # 是否从eureka上获取注册信息
    fetch-registry: false
  # eureka服务器的地址（注意：地址最后面的/eureka/是个固定值）
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  # 服务器失效时间，默认90秒
  instance:
    lease-expiration-duration-in-seconds: 15

