#Tomcat
server:
  tomcat:
    max-threads: 10
    min-spare-threads: 10
  port: 7777

#mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml